#flow_id:
#    id: flow_id
#    steps:
#        state_name:
#            next: string
#            code: string
#            message:
#                text: string


greeting:
    id: greeting
    steps:
        #        –Ω—É–∂–Ω–æ –¥–æ–±–∞–≤–ª—è—Ç—å —ç—Ç–æ—Ç —Ñ–∏–∫—Ç–∏–≤–Ω—ã–π –ø–µ—Ä–≤—ã–π —à–∞–≥. –ò–Ω–∞—á–µ –ø–µ—Ä–µ–∫–ª—é—á–µ–Ω–∏–µ –±—É–¥–µ—Ç —Ä–∞–±–æ—Ç–∞—Ç—å –Ω–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω–æ
        idle:
            next: greet
        greet:
            message:
                text: |
                    –î–æ–±—Ä—ã–π –¥–µ–Ω—å! –ß—Ç–æ–±—ã –ª—É—á—à–µ –ø–æ–º–æ—á—å –≤–∞–º, –æ—Ç–≤–µ—Ç—å—Ç–µ –Ω–∞ –Ω–µ—Å–∫–æ–ª—å–∫–æ –≤–æ–ø—Ä–æ—Å–æ–≤. 
                    –î–ª—è –Ω–∞—á–∞–ª–∞ –ø–æ–¥–µ–ª–∏—Ç–µ—Å—å –Ω–æ–º–µ—Ä–æ–º —Ç–µ–ª–µ—Ñ–æ–Ω–∞
                answers:
                    -   text: –û—Ç–ø—Ä–∞–≤–∏—Ç—å –Ω–æ–º–µ—Ä
                        request_contact: true
            code: phone
            next: ask_name
        ask_name: # —á—Ç–æ –æ–∑–Ω–∞—á–∞–µ—Ç –ø–µ—Ä–µ—Ö–æ–¥ –Ω–∞ —Å—Ç–µ–π—Ç? –Ω–∞ –Ω–µ–º –æ—Ç–ø—Ä–∞–≤–ª—è–µ—Ç—Å—è —Å–æ–æ–±—â–µ–Ω–∏–µ. –ù–æ –¥–∞–Ω–Ω—ã–µ –Ω—É–∂–Ω–æ —Å–æ–±–∏—Ä–∞—Ç—å —Å –ø—Ä–µ–¥—ã–¥—É—â–µ–≥–æ —Å—Ç–µ–ø–∞
            message:
                text: –ö–∞–∫ –≤–∞—Å –∑–æ–≤—É—Ç?
            code: name
            next: ask_status
        ask_status:
            message:
                text: –í–∞—à —Å—Ç–∞—Ç—É—Å?
                answers:
                    -   text: –°–µ–≥–æ–¥–Ω—è
                    -   text: –ó–∞–≤—Ç—Ä–∞
                    -   text: –ü–æ—Å–ª–µ–∑–∞–≤—Ç—Ä–∞
            code: status
            next: ask_email
        ask_email:
            message:
                text: –í–∞—à email
            code: email
            next: complete
        complete:
            message:
                text: 'üÜó –í–∞—à–∏ –æ—Ç–≤–µ—Ç—ã –ø–æ–º–æ–≥—É—Ç –º–Ω–µ –ø—Ä–µ–¥–æ—Å—Ç–∞–≤–∏—Ç—å –≤–∞–º –Ω–∞–∏–±–æ–ª–µ–µ —Ä–µ–ª–µ–≤–∞–Ω—Ç–Ω—É—é –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –∏ –ø–æ–¥–¥–µ—Ä–∂–∫—É. –°–ø–∞—Å–∏–±–æ, —á—Ç–æ –¥–µ–ª–∏—Ç–µ—Å—å —Å –Ω–∞–º–∏! üíñ'
#            –µ—Å–ª–∏ –Ω–µ—Ç next - —ç—Ç–æ –ø–æ—Å–ª–µ–¥–Ω–∏–π. –ù–∞ –Ω–µ–º –Ω–∏–∫–∞–∫–∏—Ö code –±—ã—Ç—å –Ω–µ –¥–æ–ª–∂–Ω–æ - —ç—Ç–æ –∑–∞–∫—Ä—ã–≤–∞—é—â–µ–µ —Å–æ–æ–±—â–µ–Ω–∏–µ, –æ—Ç –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è –ø–æ—Å–ª–µ –Ω–µ–≥–æ –Ω–µ –æ–∂–∏–¥–∞–µ—Ç—Å—è –Ω–∏–∫–∞–∫–æ–≥–æ –≤–≤–æ–¥–∞